[package]
name = "abc101"
version = "0.1.0"
authors = ["ynishimura <ynishimura0922@gmail.com>"]
edition = "2018"

# dependencies added to new project
[dependencies]

[profile.release]
lto = true
panic = 'abort'
